on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
    
jobs:
  eslint:
    name: eslint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: install deps
      run: yarn install --no-lockfile
    - name: tsc
      uses: icrawl/action-tsc@v1
